### ISSUE TITLE
Installation fails on CentOS 6.3 with Node 5.0

### ISSUE THREAD

**Issue by kadishmal** [liushoukai/node-hash-functions#2]
- node 5.0.0
- npm 3.3.6
- CentOS 6.3

```
$ uname -a
Linux breed033.dev 2.6.32-279.2.1.el6.x86_64 #1 SMP Fri Jul 20 01:55:29 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS release 6.3 (Final)
$ npm install node-hashes

> node-hashes@0.0.3 install /home1/user/apps/projectA/indexer-1.0.0/node_modules/node-hashes
> node-gyp rebuild

make: Entering directory `/home1/user/apps/projectA/indexer-1.0.0/node_modules/node-hashes/build'
  CXX(target) Release/obj.target/nodehashes/src/CalculateHash.o
In file included from /home1/user/.node-gyp/5.0.0/include/node/node.h:42,
                 from ../src/CalculateHash.cpp:14:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:336: error: expected unqualified-id before ‘using’
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:353: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:360: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:364: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:430: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: At global scope:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:469: error: expected unqualified-id before ‘using’
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:794: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:819: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:831: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: At global scope:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:856: error: expected unqualified-id before ‘using’
/home1/user/.node-gyp/5.0.0/include/node/v8.h:1093: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h:1099: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:3204: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/home1/user/.node-gyp/5.0.0/include/node/v8.h:7154: error: ‘nullptr’ was not declared in this scope
In file included from ../src/CalculateHash.cpp:15:
/home1/user/.node-gyp/5.0.0/include/node/v8-util.h: In static member function ‘static void* v8::DefaultGlobalMapTraits<K, V>::WeakCallbackParameter(v8::GlobalValueMap<K, V, v8::DefaultGlobalMapTraits<K, V> >*, const K&, v8::Local<V>)’:
/home1/user/.node-gyp/5.0.0/include/node/v8-util.h:125: error: ‘nullptr’ was not declared in this scope
/home1/user/.node-gyp/5.0.0/include/node/v8-util.h: In static member function ‘static v8::GlobalValueMap<K, V, v8::DefaultGlobalMapTraits<K, V> >* v8::DefaultGlobalMapTraits<K, V>::MapFromWeakCallbackInfo(const v8::WeakCallbackInfo<void>&)’:
/home1/user/.node-gyp/5.0.0/include/node/v8-util.h:129: error: ‘nullptr’ was not declared in this scope
make: *** [Release/obj.target/nodehashes/src/CalculateHash.o] Error 1
make: Leaving directory `/home1/user/apps/projectA/indexer-1.0.0/node_modules/node-hashes/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home1/user/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-279.2.1.el6.x86_64
gyp ERR! command "/home1/user/.nvm/versions/node/v5.0.0/bin/node" "/home1/user/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home1/user/apps/projectA/indexer-1.0.0/node_modules/node-hashes
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON reindexer@1.0.1 No description
npm WARN EPACKAGEJSON reindexer@1.0.1 No repository field.
npm WARN EPACKAGEJSON reindexer@1.0.1 license should be a valid SPDX license expression
npm ERR! Linux 2.6.32-279.2.1.el6.x86_64
npm ERR! argv "/home1/user/.nvm/versions/node/v5.0.0/bin/node" "/home1/user/.nvm/versions/node/v5.0.0/bin/npm" "install" "node-hashes"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! node-hashes@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hashes@0.0.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-hashes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-hashes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home1/user/apps/projectA/indexer-1.0.0/npm-debug.log
```

The same node 5.0.0 and npm 3.3.6 combination works fine on Mac OS X.

**Comment by kadishmal** [comment]
Seems like this is related to the Node version. Similar issues occur in other projects. Refer to https://github.com/travis-ci/travis-ci/issues/4771.

**Comment by kadishmal** [comment]
It seems to be the compiler problem. I have updated the compiler to gcc 4.8 and the build was successful.
